### ISSUE TITLE
Bridge mode

### ISSUE THREAD

**Issue by mrbluecoat** [MengJiangProject/redproxy-rs#105]
Cool project! Does it work on Linux devices in bridge mode? (e.g. a border gateway)

**Comment by bearice** [comment]
Hmm, I only tested it on an router mode gateway. But since it's using tproxy apis, a quick google search tells me that it should also works on a bridge, refs: http://people.apache.org/~amc/tiphares/bridge.html

Please leave a comment if you found it works or not 😃.

**Comment by bearice** [comment]
close as stale
