### ISSUE TITLE
Error loading provided sample configuration.

### ISSUE THREAD

**Issue by phantomcraft** [MengJiangProject/redproxy-rs#189]
I download and compiled reproxy-rs, but when I try to run for testing, it shows:

```
user@localhost:~$ /dev/shm/redproxy-rs/target/release/redproxy-rs --config /dev/shm/redproxy-rs/config.yaml
Error: parse yaml (src/config.rs:25:34)
Caused by: accessLog.format: invalid type: map, expected a YAML tag starting with '!' at line 80 column 5
```

Could you please correct the sample configuration?

**Comment by bearice** [comment]
Thanks for reporting! After a git bisect run I found that commit 382b3b67 breaks config loading process, seems to be an bad dependency update, will invegest later today. meanwhile you can still checkout the last known good tag `v0.7.0` to play with.

**Comment by phantomcraft** [comment]
Thank you!

Implement BIND and UDP ASSOCIATE too and redproxy-rs will become overkill. =)
