### ISSUE TITLE
[Improvement] splice() support

### ISSUE THREAD

**Issue by phantomcraft** [MengJiangProject/redproxy-rs#217]
I tested the performance of reproxy-rs with iperf3 and proxychains-ng and it reaches ~12000 mbps in my system. On the other hand, testing a socks5 server (3proxy) that uses splice() I get about 25000 mbps.

If implemented in redproxy-rd it would double its performance.

This is my suggestion.

There are some packages here in Github implementing splice() (it could serve as a basis):

https://github.com/ArniDagur/InstantTee

https://github.com/mre/fcat

**Comment by bearice** [comment]
Thanks for your advice, I think the main troubles are:

1. `splice()` is linux only
2. it can not work with TLS enabled sockets

But I think there could be a way to overcome these problems by falling back to normal copying functions.
I'll do some more research later.

**Comment by phantomcraft** [comment]
I think this feature is very relevant as redproxy-rs is designed mainly to provide Linux transparent proxies, in Windows should be useful when serving QUIC UDP proxies and forward ports.

But doubling redproxy-rs performance would be very welcomed.
