### ISSUE TITLE
[Question] Does QUIC connector support authentication?

### ISSUE THREAD

**Issue by phantomcraft** [MengJiangProject/redproxy-rs#223]
I couldn't find any example of authentication in file config.yaml.

Does reproxy-rs support authentication on QUIC connector?

I found this project: https://github.com/liudanking/quic-proxy

/\ Is it the same proxy type used by redproxy-rs?

**Comment by phantomcraft** [comment]
Got.

**Comment by phantomcraft** [comment]
Just another question.

The QUIC proxy used by this project is a HTTP/3 CONNECT proxy or another kind of QUIC proxy?

**Comment by bearice** [comment]
It's using QUIC as a transport protocol, aka HTTP1.1 CONNECT over QUIC.
