### ISSUE TITLE
Error: failed to read certificates (Caused by: No such file or directory)

### ISSUE THREAD

**Issue by phantomcraft** [MengJiangProject/redproxy-rs#224]
I tried to run the latest master version here: https://github.com/MengJiangProject/redproxy-rs/releases/tag/v0.8.1

But I get this error when opening:

```
# ./redproxy-rs -c config.yaml 
Error: failed to read certificates (src/common/tls.rs:223:33)
Caused by: No such file or directory (os error 2)
```

My libstd-rust is 1.61. I tried to compile with rustc 1.64 but the same error persists.

Is there something that I need to upgrade or install in order to make it work?

**Comment by bearice** [comment]
It seems just cannot read certificates,
did you generate the TLS certificates?

**Comment by bearice** [comment]
Yes, quic requires a TLS certificate to work
Generate one with openssl is fine
Ref:
https://stackoverflow.com/questions/10175812/how-to-generate-a-self-signed-ssl-certificate-using-openssl
Don’t forget to change filename in config.yaml
